import { TService } from "@/types/service";

export const suggestedPlatforms = [
  { value: "Google", label: "Google" },
  { value: "Facebook", label: "Facebook" },
  { value: "Trustpilot", label: "Trustpilot" },
  { value: "Yelp", label: "Yelp" },
  { value: "IMDB", label: "IMDB" },
  { value: "Zillow", label: "Zillow" },
  { value: "Tripadvisor", label: "Tripadvisor" },
  { value: "Apps-Android", label: "Apps-Android" },
  { value: "Apps-iPhone", label: "Apps-iPhone" },
  { value: "Glassdoor", label: "Glassdoor" },
  { value: "Indeed", label: "Indeed" },
  { value: "BusinessYab", label: "BusinessYab" },
];

// Temporary mock data – replace with real data from API later

export const mockServices: TService[] = [
  {
    platform: "Google",
    name: "Google 5 Star Reviews",
    count: "5",
    price: 49,
    deliveryTimeRange: "3-5 days",
    type: "Standard",
    isFeatured: true, 
  },
  {
    platform: "Google",
    name: "Google Local Posts",
    count: "10",
    price: 59,
    deliveryTimeRange: "2-4 days",
    type: "Standard",
    isFeatured: false,
  },
  {
    platform: "Facebook",
    name: "Facebook Page Likes",
    count: "100",
    price: 29,
    deliveryTimeRange: "1-3 days",
    type: "Standard",
    isFeatured: false,
  },
  {
    platform: "Facebook",
    name: "Facebook Reviews",
    count: "10",
    price: 39,
    deliveryTimeRange: "2-5 days",
    type: "Standard",
    isFeatured: true,
  },
  {
    platform: "Trustpilot",
    name: "Trustpilot Reviews",
    count: "5",
    price: 55,
    deliveryTimeRange: "4-6 days",
    type: "Standard",
    isFeatured: false,
  },
  {
    platform: "Trustpilot",
    name: "Trustpilot 5 Star Reviews",
    count: "10",
    price: 99,
    deliveryTimeRange: "5-7 days",
    type: "Monthly",
    isFeatured: true,
  },
  {
    platform: "Yelp",
    name: "Yelp Reviews",
    count: "5",
    price: 59,
    deliveryTimeRange: "5-7 days",
    type: "Standard",
    isFeatured: true,
  },
  {
    platform: "Yelp",
    name: "Yelp 5 Star Reviews Package",
    count: "20",
    price: 109,
    deliveryTimeRange: "7-10 days",
    type: "Monthly",
    isFeatured: false,
  },
  {
    platform: "IMDB",
    name: "IMDB Ratings",
    count: "50",
    price: 89,
    deliveryTimeRange: "3-5 days",
    type: "Standard",
    isFeatured: false,
  },
  {
    platform: "IMDB",
    name: "IMDB Pro Reviews",
    count: "100",
    price: 149,
    deliveryTimeRange: "5-8 days",
    type: "Monthly",
    isFeatured: true,
  },
  {
    platform: "Zillow",
    name: "Zillow Reviews",
    count: "10",
    price: 69,
    deliveryTimeRange: "4-6 days",
    type: "Standard",
    isFeatured: false,
  },
  {
    platform: "Zillow",
    name: "Zillow Agent Reviews",
    count: "15",
    price: 99,
    deliveryTimeRange: "6-8 days",
    type: "Monthly",
    isFeatured: false,
  },
  {
    platform: "Tripadvisor",
    name: "Tripadvisor Reviews",
    count: "5",
    price: 64,
    deliveryTimeRange: "3-5 days",
    type: "Standard",
    isFeatured: false,
  },
  {
    platform: "Tripadvisor",
    name: "Tripadvisor 5 Star Reviews",
    count: "20",
    price: 119,
    deliveryTimeRange: "6-9 days",
    type: "Monthly",
    isFeatured: false,
  },
  {
    platform: "Apps-Android",
    name: "Google Play Store Reviews",
    count: "50",
    price: 79,
    deliveryTimeRange: "4-6 days",
    type: "Standard",
    isFeatured: false,
  },
  {
    platform: "Apps-Android",
    name: "Android App Rating Boost",
    count: "100",
    price: 139,
    deliveryTimeRange: "7-10 days",
    type: "Monthly",
    isFeatured: false,
  },
  {
    platform: "Apps-iPhone",
    name: "App Store Reviews",
    count: "50",
    price: 84,
    deliveryTimeRange: "4-6 days",
    type: "Standard",
    isFeatured: false,
  },
  {
    platform: "Apps-iPhone",
    name: "iOS App Rating Package",
    count: "100",
    price: 149,
    deliveryTimeRange: "7-10 days",
    type: "Monthly",
    isFeatured: true,
  },
  {
    platform: "Glassdoor",
    name: "Glassdoor Company Reviews",
    count: "10",
    price: 74,
    deliveryTimeRange: "5-7 days",
    type: "Standard",
    isFeatured: false,
  },
  {
    platform: "Glassdoor",
    name: "Glassdoor Employer Reviews",
    count: "25",
    price: 129,
    deliveryTimeRange: "7-10 days",
    type: "Monthly",
    isFeatured: false,
  },
  {
    platform: "Indeed",
    name: "Indeed Company Reviews",
    count: "10",
    price: 69,
    deliveryTimeRange: "3-5 days",
    type: "Standard",
    isFeatured: false,
  },
  {
    platform: "Indeed",
    name: "Indeed Reviews Package",
    count: "25",
    price: 119,
    deliveryTimeRange: "6-8 days",
    type: "Monthly",
    isFeatured: false,
  },
  {
    platform: "BusinessYab",
    name: "BusinessYab Reviews",
    count: "10",
    price: 54,
    deliveryTimeRange: "2-4 days",
    type: "Standard",
    isFeatured: false,
  },
  {
    platform: "BusinessYab",
    name: "BusinessYab 5 Star Package",
    count: "20",
    price: 99,
    deliveryTimeRange: "4-6 days",
    type: "Monthly",
    isFeatured: false,
  },
];